name: Package for macOS

# workflow has to be started manually, not by events
on:
  workflow_dispatch:

jobs:
  build_and_package:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests
      - name: Package creation
        run: |
          cd st-packager
          ./package-macos.sh
      - name: Archive package
        uses: actions/upload-artifact@v3
        with:
          name: SportsTracker-macOS_x64_dmg
          path: st-packager/package/SportsTracker-*.dmg
          retention-days: 5
