name: Package for Windows

# workflow has to be started manually, not by events
on:
  workflow_dispatch:

jobs:
  build_and_package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests
      - name: Package creation
        run: |
          cd st-packager
          package-windows.bat
        shell: cmd
      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: SportsTracker-Windows_x64_exe
          path: st-packager/package/
          retention-days: 5
