name: Package for Ubuntu Linux

# workflow has to be started manually, not by events
on:
  workflow_dispatch:

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests
      - name: Package creation
        run: |
          cd st-packager
          ./package-linux.sh
      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: SportsTracker-Ubuntu_amd64_deb
          path: st-packager/package/sportstracker_*.deb
          retention-days: 5
