name: SportsTracker CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: maven
      - name: Build with Maven
        # XVFB needed for unit tests, see https://github.com/coactions/setup-xvfb
        uses: coactions/setup-xvfb@v1
        with:
          run: mvn -B package
